In [2]:
# Exercise 07:
import pandas as pd
dict={'name':["Sandeep","mahi","Umesh"],
'age':["19","21","22"]}
a=pd.DataFrame(dict,index=[True,False,True])
print(a)

          name age
True   Sandeep  19
False     mahi  21
True     Umesh  22


In [3]:
import pandas as pd
dict={'name':["Sandeep","mahi","Umesh"],
'age':["19","21","22"]}
a=pd.DataFrame(dict,index=[True,False,True])
print(a.loc[True])

         name age
True  Sandeep  19
True    Umesh  22


In [7]:
import numpy as np
arr=np.arange(16)
print("The Original array is:\n",arr)
arr=np.arange(16).reshape(2,8)
print("\nreshapedarray: \n",arr)
arr=np.arange(16).reshape(8,2)
print("\nreshaped array:\n",arr)

The Original array is:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

reshapedarray: 
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]

reshaped array:
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
